// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace UIViewT4Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\ABC Runner\Assets\Ultilities\UI\Editor\UIViewT4Template~\UIViewT4Template\UIViewGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class UIViewGenerator : UIViewGeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("///\r\n/// auto-generated please do not modified\r\n///\r\n\r\nusing System;\r\nusing Unity" +
                    "Engine;\r\n\r\npublic partial class ");
            
            #line 18 "D:\ABC Runner\Assets\Ultilities\UI\Editor\UIViewT4Template~\UIViewT4Template\UIViewGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m_ClassName));
            
            #line default
            #line hidden
            this.Write(" : UIComponent.UIView<");
            
            #line 18 "D:\ABC Runner\Assets\Ultilities\UI\Editor\UIViewT4Template~\UIViewT4Template\UIViewGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m_ClassName));
            
            #line default
            #line hidden
            this.Write(".Entity>\r\n{\r\n\t[System.Serializable]\r\n\tpublic partial class Entity\r\n\t{\r\n");
            
            #line 23 "D:\ABC Runner\Assets\Ultilities\UI\Editor\UIViewT4Template~\UIViewT4Template\UIViewGenerator.tt"

		for (int i = 0; i < m_FieldNames.Length; i++)
		{

            
            #line default
            #line hidden
            this.Write("\t\tpublic ");
            
            #line 27 "D:\ABC Runner\Assets\Ultilities\UI\Editor\UIViewT4Template~\UIViewT4Template\UIViewGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m_EntityTypes[i]));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 27 "D:\ABC Runner\Assets\Ultilities\UI\Editor\UIViewT4Template~\UIViewT4Template\UIViewGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m_FieldNames[i]));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 28 "D:\ABC Runner\Assets\Ultilities\UI\Editor\UIViewT4Template~\UIViewT4Template\UIViewGenerator.tt"

		}

            
            #line default
            #line hidden
            this.Write("\t}\r\n\r\n");
            
            #line 33 "D:\ABC Runner\Assets\Ultilities\UI\Editor\UIViewT4Template~\UIViewT4Template\UIViewGenerator.tt"

		for (int i = 0; i < m_FieldNames.Length; i++)
		{

            
            #line default
            #line hidden
            this.Write("\tpublic ");
            
            #line 37 "D:\ABC Runner\Assets\Ultilities\UI\Editor\UIViewT4Template~\UIViewT4Template\UIViewGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m_FieldTypes[i]));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 37 "D:\ABC Runner\Assets\Ultilities\UI\Editor\UIViewT4Template~\UIViewT4Template\UIViewGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m_FieldNames[i]));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n");
            
            #line 39 "D:\ABC Runner\Assets\Ultilities\UI\Editor\UIViewT4Template~\UIViewT4Template\UIViewGenerator.tt"

		}

            
            #line default
            #line hidden
            this.Write("\tpublic override void SetData(Entity data)\r\n    {\r\n        base.SetData(data);\r\n");
            
            #line 45 "D:\ABC Runner\Assets\Ultilities\UI\Editor\UIViewT4Template~\UIViewT4Template\UIViewGenerator.tt"

		for (int i = 0; i < m_FieldNames.Length; i++)
		{

            
            #line default
            #line hidden
            this.Write("\t\tthis.");
            
            #line 49 "D:\ABC Runner\Assets\Ultilities\UI\Editor\UIViewT4Template~\UIViewT4Template\UIViewGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m_FieldNames[i]));
            
            #line default
            #line hidden
            this.Write("?.SetData(this.Data?.");
            
            #line 49 "D:\ABC Runner\Assets\Ultilities\UI\Editor\UIViewT4Template~\UIViewT4Template\UIViewGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(m_FieldNames[i]));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 50 "D:\ABC Runner\Assets\Ultilities\UI\Editor\UIViewT4Template~\UIViewT4Template\UIViewGenerator.tt"

		}

            
            #line default
            #line hidden
            this.Write("    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "D:\ABC Runner\Assets\Ultilities\UI\Editor\UIViewT4Template~\UIViewT4Template\UIViewGenerator.tt"

private string _m_ClassNameField;

/// <summary>
/// Access the m_ClassName parameter of the template.
/// </summary>
private string m_ClassName
{
    get
    {
        return this._m_ClassNameField;
    }
}

private string _m_FieldTypeField;

/// <summary>
/// Access the m_FieldType parameter of the template.
/// </summary>
private string m_FieldType
{
    get
    {
        return this._m_FieldTypeField;
    }
}

private string[] _m_FieldNamesField;

/// <summary>
/// Access the m_FieldNames parameter of the template.
/// </summary>
private string[] m_FieldNames
{
    get
    {
        return this._m_FieldNamesField;
    }
}

private string[] _m_FieldTypesField;

/// <summary>
/// Access the m_FieldTypes parameter of the template.
/// </summary>
private string[] m_FieldTypes
{
    get
    {
        return this._m_FieldTypesField;
    }
}

private string[] _m_EntityTypesField;

/// <summary>
/// Access the m_EntityTypes parameter of the template.
/// </summary>
private string[] m_EntityTypes
{
    get
    {
        return this._m_EntityTypesField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool m_ClassNameValueAcquired = false;
if (this.Session.ContainsKey("m_ClassName"))
{
    this._m_ClassNameField = ((string)(this.Session["m_ClassName"]));
    m_ClassNameValueAcquired = true;
}
if ((m_ClassNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("m_ClassName");
    if ((data != null))
    {
        this._m_ClassNameField = ((string)(data));
    }
}
bool m_FieldTypeValueAcquired = false;
if (this.Session.ContainsKey("m_FieldType"))
{
    this._m_FieldTypeField = ((string)(this.Session["m_FieldType"]));
    m_FieldTypeValueAcquired = true;
}
if ((m_FieldTypeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("m_FieldType");
    if ((data != null))
    {
        this._m_FieldTypeField = ((string)(data));
    }
}
bool m_FieldNamesValueAcquired = false;
if (this.Session.ContainsKey("m_FieldNames"))
{
    this._m_FieldNamesField = ((string[])(this.Session["m_FieldNames"]));
    m_FieldNamesValueAcquired = true;
}
if ((m_FieldNamesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("m_FieldNames");
    if ((data != null))
    {
        this._m_FieldNamesField = ((string[])(data));
    }
}
bool m_FieldTypesValueAcquired = false;
if (this.Session.ContainsKey("m_FieldTypes"))
{
    this._m_FieldTypesField = ((string[])(this.Session["m_FieldTypes"]));
    m_FieldTypesValueAcquired = true;
}
if ((m_FieldTypesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("m_FieldTypes");
    if ((data != null))
    {
        this._m_FieldTypesField = ((string[])(data));
    }
}
bool m_EntityTypesValueAcquired = false;
if (this.Session.ContainsKey("m_EntityTypes"))
{
    this._m_EntityTypesField = ((string[])(this.Session["m_EntityTypes"]));
    m_EntityTypesValueAcquired = true;
}
if ((m_EntityTypesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("m_EntityTypes");
    if ((data != null))
    {
        this._m_EntityTypesField = ((string[])(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class UIViewGeneratorBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
